import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#A3B899", // Sage Green
          50: "#F5F7F3",
          100: "#E8EDE3",
          200: "#D1DBC7",
          300: "#B9C9AB",
          400: "#A3B899",
          500: "#8DA687",
          600: "#778F75",
          700: "#617863",
          800: "#4B6151",
          900: "#354A3F",
          foreground: "#ffffff",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sand: {
          DEFAULT: "#FDF8F0",
          50: "#FEFCF8",
          100: "#FDF8F0",
          200: "#FBF1E1",
          300: "#F9EAD2",
          400: "#F7E3C3",
          500: "#F5DCB4",
          600: "#F3D5A5",
          700: "#F1CE96",
          800: "#EFC787",
          900: "#EDC078",
        },
        peach: {
          DEFAULT: "#FAB49B",
          50: "#FEF7F4",
          100: "#FDEFE9",
          200: "#FBDFD3",
          300: "#F9CFBD",
          400: "#F7BFA7",
          500: "#FAB49B",
          600: "#F8A485",
          700: "#F6946F",
          800: "#F48459",
          900: "#F27443",
        },
        volcanic: {
          DEFAULT: "#5D5C61",
          50: "#F4F4F5",
          100: "#E9E9EA",
          200: "#D3D3D5",
          300: "#BDBDC0",
          400: "#A7A6AB",
          500: "#918F96",
          600: "#7B7981",
          700: "#65636C",
          800: "#5D5C61",
          900: "#4F4D57",
        },
        mint: {
          DEFAULT: "#B2D8D8",
          50: "#F7FCFC",
          100: "#EFF9F9",
          200: "#DFF3F3",
          300: "#CFEDED",
          400: "#BFE7E7",
          500: "#B2D8D8",
          600: "#9FCCCC",
          700: "#8CC0C0",
          800: "#79B4B4",
          900: "#66A8A8",
        },
        terracotta: {
          DEFAULT: "#E88873",
          50: "#FBF5F3",
          100: "#F7EBE7",
          200: "#EFD7CF",
          300: "#E7C3B7",
          400: "#DFAF9F",
          500: "#E88873",
          600: "#E3745B",
          700: "#DE6043",
          800: "#D94C2B",
          900: "#D43813",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      animation: {
        "bounce-slow": "bounce 2s infinite",
        "pulse-slow": "pulse 3s infinite",
        wiggle: "wiggle 1s ease-in-out infinite",
      },
      keyframes: {
        wiggle: {
          "0%, 100%": { transform: "rotate(-3deg)" },
          "50%": { transform: "rotate(3deg)" },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
export default config
